Redid solver to be a simple program
SDUMicroDevOps/MicroDevOps pull request #8
Opened 2022-12-01 10:57 UTC by Maje419

Running the image will still fail outside of a Kubernetes cluster, but the code works just trust me

2022-12-01 11:32 UTC, TotallyRealHolm commented on Solver/Solver.py
> +    userID = "testUser"
That is a lot of comments

2022-12-01 11:33 UTC, darkIvor commented on Solver/Solver.py
> +    userID = "testUser"
where is a lot of comments

2022-12-01 11:33 UTC, TotallyRealHolm commented on Solver/Solver.py
> +    userID = "testUser"
right here

2022-12-01 11:34 UTC, darkIvor commented on Solver/Solver.py
> +    userID = "testUser"
but there are no arguments either.

2022-12-01 11:36 UTC, TotallyRealHolm commented on Solver/Solver.py
> +            self.has_dzn_file = args[3].upper() == "TRUE"
Modern problems require modern solutions

2022-12-01 11:38 UTC, TotallyRealHolm commented on Solver/Solver.py
> +            self.has_dzn_file = args[3].upper() == "TRUE"
Try typecasting it with bool()

2022-12-01 11:40 UTC, TotallyRealHolm requested changes
Remember to remove the charp project files

2022-12-01 11:40 UTC, TotallyRealHolm commented on ServiceTests/SolverTests/SolverTests.cs
> +    {
Remember to remove the C sharp project files

2022-12-01 11:42 UTC, TotallyRealHolm commented on Solver/Dockerfile
> +COPY Examples/shortest.mzn Test/shortest.mzn
We need to remember to remove these , for the final image

2022-12-01 14:40 UTC, TotallyRealHolm commented on Solver/Solver.py
> +    #This function is here to download the files at some point
Might be good with TODO tag

2022-12-01 15:03 UTC, Maje419 reviewed
The ServiceTests have been removed

2022-12-01 15:08 UTC, TotallyRealHolm requested changes
Suggested some changes, after that LGTM.

2022-12-01 15:10 UTC, Maje419 commented on Solver/Solver.py
> +        if (len(args) == 5):
Good call. The DZN file needs to be the last argument since it is optional, so i moved the MZN file.

2022-12-02 09:39 UTC, TotallyRealHolm approved these changes
LGTM

2022-12-02 09:51 UTC, merged